"""工具基类"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional, Callable, get_type_hints
from pydantic import BaseModel
import inspect
import re


def tool_action(name: str = None, description: str = None):
    """装饰器：标记一个方法为可展开的工具 action

    用法:
        @tool_action("memory_add", "添加新记忆")
        def _add_memory(self, content: str, importance: float = 0.5) -> str:
            '''添加记忆

            Args:
                content: 记忆内容
                importance: 重要性分数
            '''
            ...

    Args:
        name: 工具名称（如果不提供，从方法名自动生成）
        description: 工具描述（如果不提供，从 docstring 提取）
    """
    def decorator(func: Callable):
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        return func
    return decorator


class ToolParameter(BaseModel):
    """工具参数定义"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class Tool(ABC):
    """工具基类

    支持两种使用模式：
    1. 普通模式：工具作为单一实体使用
    2. 可展开模式：工具可以展开为多个独立的子工具（每个子工具对应一个功能）

    展开模式支持两种实现方式：
    - 手动定义子工具类（传统方式）
    - 使用 @tool_action 装饰器自动生成（推荐）
    """

    def __init__(self, name: str, description: str, expandable: bool = False):
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        pass

    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        pass

    def get_expanded_tools(self) -> Optional[List['Tool']]:
        """自动从标记了 @tool_action 的方法生成子工具"""
        if not self.expandable:
            return None

        tools = []
        for _, method in inspect.getmembers(self, predicate=inspect.ismethod):
            if hasattr(method, '_is_tool_action'):
                # 传入 parent=self
                tool = AutoGeneratedTool(
                    method=method,
                    parent=self,
                    name=method._tool_name,
                    description=method._tool_description
                )
                tools.append(tool)
        return tools if tools else None

    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        """验证参数是否齐全"""
        required_params = [p.name for p in self.get_parameters() if p.required]
        return all(param in parameters for param in required_params)

    def to_dict(self) -> Dict[str, Any]:
        """转换为字典格式"""
        # 兼容 Pydantic V1 和 V2
        dump_method = getattr(ToolParameter, "model_dump", None) or ToolParameter.dict
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [dump_method(param) for param in self.get_parameters()]
        }

    def to_openai_schema(self) -> Dict[str, Any]:
        """转换为 OpenAI function calling schema 格式"""
        properties = {}
        required = []

        for param in self.get_parameters():
            prop = {"type": param.type, "description": param.description}
            
            if param.default is not None:
                prop["description"] += f" (默认: {param.default})"
            if param.type == "array":
                prop["items"] = {"type": "string"}

            properties[param.name] = prop
            if param.required:
                required.append(param.name)

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        }

    def __str__(self) -> str:
        return f"Tool(name={self.name})"


class AutoGeneratedTool(Tool):
    """自动生成的工具 - 从方法签名和 docstring 自动提取参数"""

    def __init__(self, method: Callable, name: str = None, description: str = None, parent: Optional['Tool'] = None):
        """
        优化: parent 改为可选，支持包装独立函数
        """
        self.method = method
        self.parent = parent

        # 生成名称
        if name is None:
            method_name = method.__name__.lstrip('_')
            # 如果有父类，加上前缀；如果是独立函数，直接用函数名
            name = f"{parent.name}_{method_name}" if parent else method_name

        # 提取描述
        if description is None:
            description = self._extract_description_from_docstring()

        super().__init__(name=name, description=description)
        self._parameters = self._parse_parameters()

    def _extract_description_from_docstring(self) -> str:
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"执行 {self.method.__name__}"
        
        # 提取第一行非空且非 Args/Returns 的内容
        for line in doc.split('\n'):
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line
        return f"执行 {self.method.__name__}"

    def _parse_parameters(self) -> List[ToolParameter]:
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""
        param_descriptions = self._parse_param_descriptions(docstring)

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue

            param_type = self._python_type_to_tool_type(type_hints.get(param_name, str))
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default
            description = param_descriptions.get(param_name, f"参数 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))
        return parameters

    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        descriptions = {}
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)
        # 匹配 param_name: 描述
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        for match in re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL):
            descriptions[match.group(1).strip()] = re.sub(r'\s+', ' ', match.group(2).strip())
        return descriptions

    def _python_type_to_tool_type(self, py_type) -> str:
        origin = getattr(py_type, '__origin__', None)
        if origin is list: return "array"
        if origin is dict: return "object"
        
        return {
            str: "string", int: "integer", float: "number",
            bool: "boolean", list: "array", dict: "object"
        }.get(py_type, "string")

    def get_parameters(self) -> List[ToolParameter]:
        return self._parameters

    def run(self, parameters: Dict[str, Any]) -> str:
        """执行方法，自动解包参数"""
        return self.method(**parameters)
