"""工具注册表 - HelloAgents原生工具系统"""

from typing import Optional, Callable, Any, Dict
from .base import Tool, AutoGeneratedTool

class ToolRegistry:
    """HelloAgents工具注册表"""
    
    def __init__(self):
        self._tools: dict[str, Tool] = {}

    def register_tool(self, tool: Tool, auto_expand: bool = True):
        """注册Tool对象"""
        if auto_expand and hasattr(tool, 'expandable') and tool.expandable:
            expanded_tools = tool.get_expanded_tools()
            if expanded_tools:
                for sub_tool in expanded_tools:
                    self._register_single(sub_tool)
                print(f"✅ 工具 '{tool.name}' 已展开为 {len(expanded_tools)} 个独立工具")
                return

        self._register_single(tool)

    def register_function(self, name_or_func, description: str = None, func: Callable = None):
        """
        直接注册函数作为工具 (兼容新旧两种调用方式)
        
        旧代码调用: register_function("tool_name", "工具描述", my_func)
        新代码调用: register_function(my_func) 或 register_function(my_func, name="tool_name", description="描述")
        """
        # 智能识别参数类型
        if callable(name_or_func):
            # 新方式：第一个参数直接是函数
            actual_func = name_or_func
            actual_name = getattr(description, '__name__', None) if description else None
            actual_desc = func if isinstance(func, str) else None
        else:
            # 旧方式：name, description, func
            actual_func = func
            actual_name = name_or_func
            actual_desc = description
            
        if actual_func is None:
            raise ValueError("必须提供要注册的函数")
            
        tool = AutoGeneratedTool(method=actual_func, name=actual_name, description=actual_desc, parent=None)
        self._register_single(tool)

    def _register_single(self, tool: Tool):
        """内部统一注册方法"""
        if tool.name in self._tools:
            print(f"⚠️ 警告：工具 '{tool.name}' 已存在，将被覆盖。")
        self._tools[tool.name] = tool
        print(f"✅ 工具 '{tool.name}' 已注册。")

    def unregister(self, name: str):
        """注销工具"""
        if name in self._tools:
            del self._tools[name]
            print(f"🗑️ 工具 '{name}' 已注销。")
        else:
            print(f"⚠️ 工具 '{name}' 不存在。")

    def get_tool(self, name: str) -> Optional[Tool]:
        """获取Tool对象"""
        return self._tools.get(name)

    def get_function(self, name: str) -> Optional[Callable]:
        """获取工具执行函数 (兼容旧代码)"""
        tool = self.get_tool(name)
        return tool.run if tool else None

    def execute_tool(self, name: str, parameters: Any) -> str:
        """
        执行工具 (兼容新旧调用)
        
        新代码: execute_tool("name", {"key": "value"})  # 推荐字典
        旧代码: execute_tool("name", "input_text")      # 兼容纯字符串
        """
        tool = self._tools.get(name)
        if not tool:
            return f"错误：未找到名为 '{name}' 的工具。"

        try:
            # 兼容旧代码：如果传入的是字符串，自动转换为 {"input": "..."} 结构
            if isinstance(parameters, str):
                parameters = {"input": parameters}
            return tool.run(parameters)
        except Exception as e:
            return f"错误：执行工具 '{name}' 时发生异常: {str(e)}"

    def get_tools_description(self) -> str:
        """获取所有可用工具的格式化描述字符串 (兼容旧代码)"""
        descriptions = [f"- {tool.name}: {tool.description}" for tool in self._tools.values()]
        return "\n".join(descriptions) if descriptions else "暂无可用工具"

    def get_openai_schemas(self) -> list[dict]:
        """获取所有工具的 OpenAI Schema 列表"""
        return [tool.to_openai_schema() for tool in self._tools.values()]

    def list_tools(self) -> list[str]:
        """列出所有工具名称"""
        return list(self._tools.keys())

    def get_all_tools(self) -> list[Tool]:
        """获取所有Tool对象 (兼容旧代码)"""
        return list(self._tools.values())

    def clear(self):
        """清空所有工具"""
        self._tools.clear()
        print("🧹 所有工具已清空。")


# 全局工具注册表
global_registry = ToolRegistry()
